### ISSUE TITLE
ModuleNotFoundError: No module named 'src.utils'

### ISSUE THREAD

**Issue by chrundle** [kayween/local_bo_mpd#1]
Hello, I hope you are doing well. I am interested in your technique and attempted to run the examples outlined in the readme, however, I encounter an error when trying to run any of the examples. For instance, when trying to run `python run_synthetic_experiment.py -c ./configs/synthetic_experiment/mpd_default.yaml -cd ./configs/synthetic_experiment/generate_data_default.yaml` (as outlined in the README) I receive the error:

```
Traceback (most recent call last):
  File "run_synthetic_experiment.py", line 10, in <module>
    from src import config
  File "/p/lustre2/chrundle/zoo-er/local-bo-mpd/src/config.py", line 8, in <module>
    from src.optimizers import (
  File "/p/lustre2/chrundle/zoo-er/local-bo-mpd/src/optimizers.py", line 18, in <module>
    from src.utils import train_model
ModuleNotFoundError: No module named 'src.utils'
```

I grep'ed the repo and did not find a definition of `train_model` anywhere else (on the off chance it was relocated from `utils` for public release) so I assume that the public repo is missing a`src/utils.py` file.

Thank you for making your code publicly available and I hope that you are able to resolve this issue soon.

**Comment by kayween** [comment]
Hi @chrundle, thanks for spotting this issue. We are fixing it. Will get back to you once the module is added.

**Comment by kayween** [comment]
Hi @chrundle , we have removed the dependency on `src/utils.py`. We also have updated the package requirement. Be sure to use the updated `environment.yaml` to install the conda environment.

The code should run now. Let me know if you run into issues.

**Comment by chrundle** [comment]
@kayween 

Thank you very much for the quick response and fix. I was able to run the synthetic test function experiments successfully. I'll go ahead and close this issue now.
